### ISSUE TITLE
Circular Readme reference

### ISSUE THREAD

**Issue by pburghadam** [AutomationAnywhere/A2019-JSON_ParserPackage-160940#1]
The documentation is a circular reference.  The AA bot store page says to check GitHub's readme and the GitHub readme points to the AA Bot store page.  Where is the documentation?

**Comment by micahman33** [comment]
Hey @pburghadam - thanks for pointing this discrepancy out. The Bot Store page has now been updated and has a link with the documentation on the right-hand column.
